### ISSUE TITLE
The version number seems to be wrong

### ISSUE THREAD

**Issue by pablogit** [pkp/pln#89] opened 2024-04-16 15:37 UTC
Hi,

We try to update the plugin from OJS 3.3.0.15 and we have the massage that the new version is 2.0.4.3 instead of 2.0.4.4, is this a typo here: 

https://github.com/pkp/pln/blob/587191959808591b5cc8c5e8a09dc20d8cd20f17/upgrade.xml#L14C1-L14C28

Best regards,
Pablo

**Comment by jonasraoni** [comment] 2024-04-22 13:00
Thanks for the report!
Closing as a duplicate of https://github.com/pkp/pln/issues/88

**Closed as not planned by jonasraoni** 2024-04-22 13:00 UTC
